### ISSUE TITLE
Connection to a Hidden Network

### ISSUE THREAD

**Issue by alde103** [nerves-project/nerves_network#91]
### Environment

* Elixir version (`elixir -v`): 
Elixir 1.7.3 (compiled with Erlang/OTP 21)
* Nerves environment: (`mix nerves.env --info`)

|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_br
  Vsn:         1.5.2
  Type:        system_platform
  BuildRunner: nil

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.5.0
  Type:        toolchain_platform
  BuildRunner: nil

  Pkg:         nerves_system_rpi3
  Vsn:         1.5.0
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.1.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

|nerves_bootstrap| Loadpaths Start

Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     rpi3
  toolchain:  /home/alde/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.1.0
  system:     /home/alde/.nerves/artifacts/nerves_system_rpi3-portable-1.5.0
  app:        /home/alde/Documents/Elixir/Nerves/repos/eliot-nerves

|nerves_bootstrap| Loadpaths End

* Additional information about your host, target hardware or environment that
  may help
host : Ubuntu 18.04

### Current behavior

I try to connect to a hidden network,  the hidden network appear in Nerves.Network.scan("wlan0") as:
`%{
    age: 0,
    beacon_int: 100,
    bssid: "the mac address",
    capabilities: 1041,
    est_throughput: 54000,
    flags: "[WPA2-PSK-CCMP][ESS]",
    freq: 2412,
    id: 11,
    ie: "x",
    level: -39,
    noise: -89,
    qual: 0,
    snr: 50,
    ssid: nil,
    tsf: 0
  }`
it appears that the network is associated, as shown in Logger.
`19:27:55.020 [info]  WiFiManager(wlan0): ignoring event: {:"CTRL-EVENT-BSS-ADDED", 1, "the mac address"}`
but is not connecting, however making visible the network the device(rpi3) connects to the network.
### Expected behavior
connect to the associated networks.

**Comment by ConnorRigby** [comment]
I am able to connect to hidden networks. I suspect this has been fixed in recent updates to `nerves_network`. Feel free to reopen if the latest version doesn't work and i will further investigate

**Comment by alde103** [comment]
Hello, thanks for checking this issue, however, I'm still having the issue :(, how do you spawn your hidden network??, I use [`create_ap` ](https://github.com/oblique/create_ap) and a tp-link USB Wifi Adapter, I started thinking that the bug maybe in that project, however, my phone can connect to the hidden network and the rpi only connects when I make visible the network, the project that I use for the test is [here](https://github.com/alde103/rpi0_lab). 
Thanks in advance.

**Comment by alde103** [comment]
This [comment](https://github.com/nerves-project/nerves_interim_wifi/issues/17) shows the fix; the fix was to add `scan_ssid: 1` to the network configuration :).

**Comment by ConnorRigby** [comment]
Hey thanks for checking this out! I will be sure to add that to the docs and maybe we can default that to set.

**Comment by alde103** [comment]
I would suggest to put it only in the docs, because it appears that `scan_ssid: 1` adds [latency](https://www.raspberrypi.org/forums/viewtopic.php?t=25104) and other rare things haa, maybe this [docs](http://w1.fi/cgit/hostap/plain/wpa_supplicant/wpa_supplicant.conf) would help.
